import Link from "next/link";
import { ArrowLeft, ArrowUpRight, BarChart3, Bot, BriefcaseBusiness, CalendarDays, CheckCircle2, CircleDollarSign, FileText, LockKeyhole, Megaphone, MessageCircle, Plug, Plus, Search, Settings2, ShieldCheck, Users, Workflow } from "lucide-react";
import "../dashboard.css";
import "./section.css";

const sections: Record<string, { title: string; eyebrow: string; description: string; icon: typeof Users; accent: string; stats: string[]; actions: string[]; rows: string[] }> = {
  crm: { title: "CRM", eyebrow: "RELATIONSHIPS / 01", description: "Keep every lead, conversation, and opportunity moving with context your team can trust.", icon: Users, accent: "lime", stats: ["128|Open leads|12.8% up", "£182k|Pipeline value|This quarter", "34%|Win rate|4.2% up"], actions: ["Add a lead", "Import contacts", "Ask AI to find follow-ups"], rows: ["Aster & Co.|Proposal sent|£12,400", "Cedar Health|Discovery call|£8,900", "Morrow Studio|Negotiation|£21,600"] },
  clients: { title: "Clients", eyebrow: "RELATIONSHIPS / 02", description: "A calm, complete view of the people and businesses behind the work.", icon: Users, accent: "violet", stats: ["24|Active clients|6 new this year", "92%|Retention|8.1% up", "4.8/5|Client sentiment|Last 30 days"], actions: ["Add client", "Invite to portal", "Export client list"], rows: ["Northstar Labs|4 active projects|Healthy", "Atlas Health|2 active projects|Attention", "Morrow Studio|1 active project|Healthy"] },
  projects: { title: "Projects", eyebrow: "DELIVERY / 01", description: "See the shape of every engagement, from the first milestone to final delivery.", icon: BriefcaseBusiness, accent: "orange", stats: ["08|Active projects|3 due this week", "76%|On-time delivery|6.4% up", "17|Open blockers|4 critical"], actions: ["New project", "Create from contract", "View workload"], rows: ["Northstar brand system|82% complete|On track", "Atlas SEO sprint|61% complete|Needs attention", "Morrow launch campaign|44% complete|In review"] },
  calendar: { title: "Calendar", eyebrow: "COORDINATION / 01", description: "One shared rhythm for meetings, deadlines, availability, and the moments that move work forward.", icon: CalendarDays, accent: "violet", stats: ["07|Meetings today|2 client-facing", "14|Deadlines|Next 7 days", "82%|Availability|Team capacity"], actions: ["Schedule meeting", "Add deadline", "Connect Google Calendar"], rows: ["Weekly studio stand-up|Today · 09:30|Everyone", "Northstar client review|Today · 11:00|45 minutes", "Atlas SEO report|Tomorrow · 16:00|Due date"] },
  marketing: { title: "Marketing", eyebrow: "GROWTH / 01", description: "Bring campaigns, SEO, content, paid media, and performance into one clear operating view.", icon: Megaphone, accent: "lime", stats: ["£42.8k|Ad spend|This month", "3.8x|ROAS|0.6x up", "1,248|Qualified leads|Across channels"], actions: ["New campaign", "Connect ad account", "Generate report"], rows: ["Morrow launch campaign|Paid + social|3.8x ROAS", "Atlas organic growth|SEO|28% traffic up", "Northstar thought leadership|Content|In production"] },
  finance: { title: "Finance", eyebrow: "MONEY / 01", description: "Know what has been earned, collected, spent, and needs attention next.", icon: CircleDollarSign, accent: "orange", stats: ["£24,860|Collected|This month", "£8,420|Outstanding|2 overdue", "£16,440|Profit|66% margin"], actions: ["Create invoice", "Record payment", "Send reminders"], rows: ["Invoice #1048|Northstar Labs|£3,200 · Paid", "Invoice #1047|Atlas Health|£2,850 · Due today", "Invoice #1043|Cedar Health|£1,240 · Overdue"] },
  documents: { title: "Documents", eyebrow: "KNOWLEDGE / 01", description: "Keep contracts, reports, proposals, and the details behind great work easy to find.", icon: FileText, accent: "violet", stats: ["248|Total files|Across workspaces", "18|Needs review|3 contracts", "100%|Organized|AI indexed"], actions: ["Upload document", "Create proposal", "Ask AI to extract"], rows: ["Northstar agreement|Contract|Updated today", "Atlas SEO report|Report|September 2026", "Morrow campaign brief|Brief|Needs review"] },
  communication: { title: "Communication", eyebrow: "CONNECTIONS / 01", description: "Keep email, messages, meetings, and internal context attached to the work that matters.", icon: MessageCircle, accent: "lime", stats: ["42|Unread messages|8 need reply", "16|Client threads|This week", "94%|Response rate|3.1% up"], actions: ["Compose message", "Connect Gmail", "View inbox"], rows: ["Northstar Labs|Homepage direction|12 min ago", "Atlas Health|Report questions|48 min ago", "Internal Delivery|Stand-up notes|Yesterday"] },
  automation: { title: "Automation", eyebrow: "SYSTEMS / 01", description: "Turn repeatable work into dependable growth systems, with approvals around every external or financial action.", icon: Workflow, accent: "orange", stats: ["06|Growth workflows|2 event-driven", "01|Approval gate|External messages", "100%|Runs audited|Database trail"], actions: ["Create workflow", "Browse templates", "View run history"], rows: ["Lead intake routing|New contact enquiry|Ready", "Project handoff|Project assigned|Ready", "Delivery risk watch|Deadline approaching|Approval required"] },
  "ai-agents": { title: "AI Agents", eyebrow: "INTELLIGENCE / 01", description: "Give your team permission-aware intelligence that proposes useful next actions with evidence.", icon: Bot, accent: "violet", stats: ["06|Active agents|All monitored", "248|Suggestions|This month", "91%|Accepted|By your team"], actions: ["Ask AI", "Configure agent", "Review approvals"], rows: ["Executive briefing|Daily at 08:00|Last run today", "Project manager|At-risk detection|3 signals", "Finance agent|Receivables watch|2 approvals"] },
  reports: { title: "Reports", eyebrow: "INTELLIGENCE / 02", description: "Turn operational signals into clear decisions for leadership, teams, and clients.", icon: BarChart3, accent: "lime", stats: ["32|Saved reports|8 scheduled", "£24.8k|Revenue view|This month", "06|AI insights|Need review"], actions: ["Build report", "Schedule report", "Export data"], rows: ["Executive operating review|Company|Updated today", "Marketing performance|Marketing|Updated yesterday", "Northstar client report|Client|Due Friday"] },
  integrations: { title: "Integrations", eyebrow: "CONNECTIONS / 02", description: "Connect the tools your company already uses without losing control of your data.", icon: Plug, accent: "orange", stats: ["04|Connected|Healthy", "07|Available|Ready to connect", "0|Sync errors|Last 24 hours"], actions: ["Browse integrations", "Connect service", "View sync logs"], rows: ["Google Calendar|Connected|Synced 2 min ago", "Gmail|Connected|Synced 8 min ago", "Google Ads|Not connected|Connect now"] },
  access: { title: "Access & Permissions", eyebrow: "CONTROL / 01", description: "Make access clear, intentional, and appropriate to every role, team, client, and sensitive record.", icon: ShieldCheck, accent: "violet", stats: ["12|Roles|4 custom", "86|Permissions|Least privilege", "24|Users|2 pending"], actions: ["Create role", "Invite user", "Review access"], rows: ["Owner|Full organization|2 members", "Marketing team|Campaigns + clients|6 members", "Client users|Portal only|16 members"] },
  "audit-logs": { title: "Audit Logs", eyebrow: "CONTROL / 02", description: "A reliable record of what changed, who changed it, and where the action came from.", icon: FileText, accent: "lime", stats: ["1,284|Events today|All systems", "0|Critical alerts|No anomalies", "100%|Coverage|Protected actions"], actions: ["Filter events", "Export log", "Configure retention"], rows: ["Alex created a project|Projects|2 min ago", "AI generated report|AI Agents|18 min ago", "Jamie completed a task|Tasks|42 min ago"] },
  "people-intelligence": { title: "People Intelligence", eyebrow: "PEOPLE / 02", description: "Review evidence around recognition, growth, support, and risk without reducing people to a single score.", icon: Users, accent: "violet", stats: ["06|Review signals|Evidence based", "03|Recognition candidates|Human review", "00|Auto-decisions|Never automatic"], actions: ["Start review cycle", "View evidence", "Configure approvals"], rows: ["Jamie Kim|Recognition review|Evidence ready", "Ravi Nair|Support plan review|Manager + HR", "Samira Patel|Promotion discussion|Needs calibration"] },
  team: { title: "Team", eyebrow: "PEOPLE / 01", description: "Understand capacity, contribution, and the work your team needs next.", icon: Users, accent: "lime", stats: ["24|Team members|4 departments", "76%|Capacity|Healthy balance", "08|Open roles|2 urgent"], actions: ["Invite teammate", "View workload", "Review performance"], rows: ["Jamie Kim|SEO Specialist|At capacity", "Ravi Nair|Project Manager|Available", "Samira Patel|Client Success|Balanced"] },
  settings: { title: "Settings", eyebrow: "CONTROL / 03", description: "Shape your workspace, defaults, notifications, and operating preferences.", icon: Settings2, accent: "violet", stats: ["04|Workspace rules|Configured", "12|Notification rules|Active", "100%|Profile setup|Complete"], actions: ["Edit workspace", "Manage notifications", "Security settings"], rows: ["Workspace profile|L. R. Tech Solutions|Configured", "Notification preferences|Team defaults|Configured", "Security controls|MFA and sessions|Review"] },
};

export default async function SectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  const data = sections[section] ?? sections.clients;
  const Icon = data.icon;
  return <div className="section-shell"><header className="section-topbar"><Link href="/dashboard" className="section-back"><ArrowLeft size={16} /> Dashboard</Link><div className="section-top-actions"><button><Search size={16} /> Search</button><button><Settings2 size={16} /></button><span className="section-user">AM</span></div></header><main className="section-content"><div className="section-hero"><div className={`section-icon ${data.accent}`}><Icon size={24} /></div><div><span className="section-eyebrow">{data.eyebrow}</span><h1>{data.title}</h1><p>{data.description}</p></div><div className="section-hero-actions"><button className="section-primary"><Plus size={16} /> {data.actions[0]}</button><button className="section-secondary">{data.actions[1]} <ArrowUpRight size={14} /></button></div></div><div className="section-stats">{data.stats.map((stat) => { const [value, label, note] = stat.split("|"); return <article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; })}</div><div className="section-layout"><section className="section-table-card"><div className="section-card-heading"><div><span>LIVE VIEW</span><h2>Recent activity</h2></div><button>View all <ArrowUpRight size={14} /></button></div><div className="section-table"><div className="section-table-head"><span>NAME</span><span>CONTEXT</span><span>STATUS / VALUE</span></div>{data.rows.map((row) => { const [name, context, status] = row.split("|"); return <div className="section-table-row" key={name}><div><span className={`row-icon ${data.accent}`}><Icon size={15} /></span><b>{name}</b></div><span>{context}</span><strong>{status}</strong><ArrowUpRight size={15} /></div>; })}</div></section><aside className="section-side-card"><span className="section-eyebrow">QUICK ACTIONS</span><h2>Move the work forward.</h2><p>Everything here is connected to your workspace, permissions, and the people doing the work.</p>{data.actions.map((action, index) => <button key={action}><span>{String(index + 1).padStart(2, "0")}</span>{action}<ArrowUpRight size={14} /></button>)}<div className="secure-note"><LockKeyhole size={14} /> Permission-aware workspace</div></aside></div><div className="section-footer-note"><CheckCircle2 size={15} /> This workspace is ready for real data, integrations, and role-based access.</div></main></div>;
}
