"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { Check, ImagePlus, Link as LinkIcon, Save, UserRound } from "lucide-react";

type Profile = { name: string; email: string; role: string; department: string; team: string; title: string; bio?: string; avatar?: string; links?: { website?: string; linkedin?: string; github?: string; instagram?: string } };

export function ProfileEditor() {
  const [profile, setProfile] = useState<Profile | null>(null); const [form, setForm] = useState({ name: "", title: "", department: "", team: "", bio: "", website: "", linkedin: "", github: "", instagram: "" }); const [avatar, setAvatar] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/team/profile").then((response) => response.ok ? response.json() : response.json().then((body) => Promise.reject(new Error(body.message)))).then((body) => { const next = body.profile as Profile; setProfile(next); setAvatar(next.avatar ?? ""); setForm({ name: next.name, title: next.title, department: next.department, team: next.team, bio: next.bio ?? "", website: next.links?.website ?? "", linkedin: next.links?.linkedin ?? "", github: next.links?.github ?? "", instagram: next.links?.instagram ?? "" }); }).catch((reason) => setError(reason.message)); }, []);
  function change(event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) { setForm((current) => ({ ...current, [event.target.name]: event.target.value })); }
  function photo(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/") || file.size > 1_000_000) { setError("Choose an image under 1 MB."); return; } const reader = new FileReader(); reader.onload = () => setAvatar(String(reader.result)); reader.readAsDataURL(file); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const response = await fetch("/api/team/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, title: form.title, department: form.department, team: form.team, bio: form.bio, avatar, links: { website: form.website, linkedin: form.linkedin, github: form.github, instagram: form.instagram } }) }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.message ?? "Profile could not be saved."); else { setProfile(body.profile); setMessage("Profile saved for your workspace."); } setSaving(false); }
  if (error && !profile) return <div className="profile-error">{error}</div>;
  return <form className="profile-editor" onSubmit={save}><div className="profile-editor-intro"><div><span className="section-eyebrow">YOUR IDENTITY / PRIVATE PROFILE</span><h2>Make your profile useful.</h2><p>Your team sees the context you choose to share. Role and permissions stay controlled by the organization.</p></div><button className="profile-save" disabled={saving}><Save size={15} /> {saving ? "Saving..." : "Save profile"}</button></div><div className="profile-editor-grid"><section className="profile-card profile-card-main"><div className="profile-photo-row"><div className="profile-photo">{avatar ? <img src={avatar} alt="Profile preview" /> : <UserRound size={28} />}</div><label className="photo-button"><ImagePlus size={15} /> Upload photo<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={photo} /></label><span>PNG, JPG, WEBP or GIF · 1 MB max</span></div><div className="profile-form-grid"><label>Full name<input name="name" value={form.name} onChange={change} required /></label><label>Professional title<input name="title" value={form.title} onChange={change} placeholder="e.g. Senior Project Manager" /></label><label>Department<input name="department" value={form.department} onChange={change} /></label><label>Team<input name="team" value={form.team} onChange={change} /></label></div><label>Bio <span className="profile-counter">{form.bio.length}/1200</span><textarea name="bio" value={form.bio} onChange={change} maxLength={1200} rows={5} placeholder="What do you own, and how can teammates work well with you?" /></label></section><aside className="profile-card profile-links-card"><div className="profile-links-heading"><LinkIcon size={17} /><div><b>Public links</b><small>Only links you provide are shown.</small></div></div>{["website", "linkedin", "github", "instagram"].map((name) => <label key={name}>{name}<input name={name} value={form[name as keyof typeof form]} onChange={change} placeholder={`https://${name}.com/...`} /></label>)}<div className="profile-role-note"><Check size={14} /><span><b>{profile?.role ?? "Workspace"}</b> · {profile?.email}<small>Your role and email cannot be changed here.</small></span></div></aside></div>{error && <div className="profile-error">{error}</div>}{message && <div className="profile-success"><Check size={15} /> {message}</div>}</form>;
}
