"use client";

import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowRight, Check, ChevronDown, CirclePlay, FileText, LockKeyhole, Menu, Play, Quote, Sparkles, Star, X, Zap } from "lucide-react";

const navItems = ["Services", "How it works", "The journal", "Reviews"];
const subjects = ["your thinking", "your deadline", "your next move", "your standard"];
const services = [
  { number: "01", title: "Research & essays", text: "A sharper argument, a stronger voice, and sources that actually move the work forward.", tone: "lime", tag: "Most requested" },
  { number: "02", title: "Dissertations", text: "From first question to final chapter — an experienced academic in your corner, end to end.", tone: "violet", tag: "High stakes" },
  { number: "03", title: "Data & analysis", text: "Make the numbers make sense. Clear methodology, clean insight, zero spreadsheet panic.", tone: "orange", tag: "STEM + social" },
];
const steps = [["01", "Tell us the brief", "Share your idea, your rubric, or just the problem keeping you up."], ["02", "Meet your person", "We match you with a specialist who speaks your subject and your language."], ["03", "Make it yours", "Review, question, refine. You stay in control until it feels completely yours."]];

export default function StudioLanding() {
  const [menuOpen, setMenuOpen] = useState(false), [subject, setSubject] = useState(0), [email, setEmail] = useState(""), [sent, setSent] = useState(false);
  useEffect(() => { const timer = window.setInterval(() => setSubject((current) => (current + 1) % subjects.length), 2400); return () => window.clearInterval(timer); }, []);
  const scrollTo = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  return <div className="site-shell">
    <div className="aurora aurora-one" /><div className="aurora aurora-two" />
    <header className="site-header"><a className="brand" href="#top" aria-label="Lumen home"><span className="brand-mark"><Sparkles size={15} /></span><span>Lumen<span className="brand-dot">.</span></span></a><nav className={`main-nav ${menuOpen ? "is-open" : ""}`}>{navItems.map((item) => <button key={item} onClick={() => scrollTo(item === "The journal" ? "journal" : item === "How it works" ? "process" : item === "Reviews" ? "reviews" : "services")}>{item}{item === "Services" && <ChevronDown size={14} />}</button>)}<a className="mobile-dashboard" href="/dashboard">Open dashboard <span>↗</span></a><button className="mobile-cta" onClick={() => scrollTo("start")}>Start a brief <span>↗</span></button></nav><a className="header-dashboard" href="/dashboard">Dashboard <span>↗</span></a><button className="header-cta" onClick={() => scrollTo("start")}>Start a brief <span>↗</span></button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></header>
    <main id="top">
      <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> The academic studio for ambitious minds</div><h1>Make room for<br /><em>better</em> <span className="rotating-word">{subjects[subject]}</span><span className="cursor-line" /></h1><p className="hero-lede">Expert academic support, without the academic theatre. Think clearer, move faster, and submit work you’re proud to put your name on.</p><div className="hero-actions"><button className="button button-dark" onClick={() => scrollTo("start")}>Find your specialist <ArrowRight size={17} /></button><button className="play-link" onClick={() => scrollTo("process")}><span><Play size={12} fill="currentColor" /></span> See how it works</button></div><div className="hero-proof"><div className="avatar-stack"><span>AM</span><span>JK</span><span>RN</span><span>+</span></div><div><div className="stars">★★★★★ <strong>4.9/5</strong></div><small>Loved by 12,000+ students</small></div></div></div><div className="hero-art" aria-label="Lumen academic support preview"><div className="orbit orbit-large" /><div className="orbit orbit-small" /><div className="hero-note note-top"><span className="note-icon lime-bg"><Check size={15} /></span><span><b>Brief understood</b><small>Matched in 08 min</small></span></div><div className="hero-note note-bottom"><span className="note-icon purple-bg"><Zap size={15} /></span><span><b>Momentum unlocked</b><small>Chapter 02 · 84% sharper</small></span></div><div className="document-card"><div className="document-top"><span className="mini-logo"><Sparkles size={11} /></span><span>lumen / studio note</span><span className="doc-dots">•••</span></div><div className="document-title"><span>01</span><div><small>FIELD NOTES / 24.09.26</small><h3>The argument<br /><i>beneath</i> the noise.</h3></div></div><div className="document-lines"><span /><span /><span className="short" /></div><div className="document-chart"><span /><span /><span /><span /><span /><span /><i>clarity</i></div><div className="document-footer"><span>Research / Structure / Voice</span><ArrowDownRight size={17} /></div></div><div className="art-label">A calmer way<br /><b>to get serious.</b></div></div><div className="scroll-cue"><span>Scroll to explore</span><ArrowDownRight size={16} /></div></section>
      <section className="signal-strip"><div className="container signal-inner"><span>Built for the moments that matter</span><div className="signal-items"><b>01 <i>—</i> Human expertise</b><b>02 <i>—</i> Thoughtful process</b><b>03 <i>—</i> Work that sounds like you</b></div></div></section>
      <section className="section services-section" id="services"><div className="container"><div className="section-heading"><div><div className="eyebrow">What we do / 01</div><h2>Big brief?<br /><em>Good.</em></h2></div><p>There’s no one-size-fits-all here. Lumen brings the right specialist, the right thinking, and a little more calm to whatever’s next.</p></div><div className="service-grid">{services.map((service) => <article key={service.number} className={`service-card ${service.tone}`}><div className="card-top"><span>{service.number}</span><span className="service-tag">{service.tag}</span></div><div className="service-icon"><FileText size={21} /></div><h3>{service.title}</h3><p>{service.text}</p><button onClick={() => scrollTo("start")}>Explore <span>↗</span></button></article>)}</div></div></section>
      <section className="section process-section" id="process"><div className="container process-layout"><div className="process-intro"><div className="eyebrow">The Lumen method / 02</div><h2>Less friction.<br /><em>More flow.</em></h2><p>Good work rarely comes from more pressure. It comes from the right questions, asked at the right time.</p><button className="text-button" onClick={() => scrollTo("start")}>Start with a question <ArrowRight size={17} /></button></div><div className="steps">{steps.map(([num, title, text]) => <div className="step" key={num}><span className="step-number">{num}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowDownRight className="step-arrow" size={18} /></div>)}</div></div></section>
      <section className="quote-section" id="reviews"><div className="quote-inner"><Quote className="quote-mark" size={48} /><blockquote>“Lumen didn’t just help me finish my dissertation. They helped me understand what I was trying to say.”</blockquote><div className="quote-person"><span className="person-avatar">SP</span><span><b>Samira Patel</b><small>MA Psychology · University of Leeds</small></span></div></div><div className="quote-side">TRUSTED BY<br /><strong>12,000+</strong><br />bright minds</div></section>
      <section className="section journal-section" id="journal"><div className="container"><div className="section-heading compact"><div><div className="eyebrow">From the journal / 03</div><h2>Thoughts for<br /><em>the in-between.</em></h2></div><button className="text-button">Read the journal <span>↗</span></button></div><div className="journal-grid"><article className="journal-feature"><div className="journal-art art-one"><span>THE<br /><i>SPACE</i><br />TO THINK</span></div><div className="article-meta">FIELD NOTE <span>·</span> 06 MIN READ</div><h3>How to find the thread when your thinking feels tangled.</h3><button className="read-link">Read note <ArrowRight size={15} /></button></article><article className="journal-feature"><div className="journal-art art-two"><CirclePlay size={38} strokeWidth={1.2} /><span>ON<br /><i>PROCESS</i></span></div><div className="article-meta">STUDIO SESSION <span>·</span> 12 MIN WATCH</div><h3>The 3 questions that turn a blank page into a beginning.</h3><button className="read-link">Watch session <ArrowRight size={15} /></button></article></div></div></section>
      <section className="start-section" id="start"><div className="container start-inner"><div><div className="eyebrow">Your next chapter / 04</div><h2>Ready when<br /><em>you are.</em></h2><p>Tell us where you’re at. We’ll take it from there — no pressure, no jargon, no judgment.</p></div><form className="start-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><label htmlFor="email">Your email address</label><div className="input-wrap"><input id="email" type="email" required placeholder="you@example.com" value={email} onChange={(event) => setEmail(event.target.value)} /><button type="submit" aria-label="Submit email">{sent ? <Check size={20} /> : <span>↗</span>}</button></div><small>{sent ? "You’re on the list. We’ll be in touch soon." : "We’ll send one useful thing. Never noise."}</small></form></div></section>
    </main>
    <footer className="site-footer"><div className="container footer-top"><a className="brand" href="#top"><span className="brand-mark"><Sparkles size={15} /></span><span>Lumen<span className="brand-dot">.</span></span></a><p>Academic support for people<br />who care about the work.</p><div className="footer-links"><a href="#services">Services</a><a href="#process">Our method</a><a href="#journal">Journal</a><a href="#start">Contact</a></div></div><div className="container footer-bottom"><span>© 2026 Lumen Studio</span><span><LockKeyhole size={13} /> Private by design</span><span>Made for the next idea <Sparkles size={13} /></span></div></footer>
  </div>;
}
