"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, Plus, Search, UserRound, X } from "lucide-react";
import { getRoleProfile } from "../lib/role-profiles";

type User = { id: string; name: string; email: string; role: string; department: string; team: string; title: string; status: string };
const roles = ["owner", "manager", "employee", "finance", "hr", "client"];

export function TeamDirectory() {
  const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/team/users").then((response) => response.ok ? response.json() : response.json().then((body) => Promise.reject(new Error(body.message)))).then((body) => setUsers(body.users)).catch((reason) => setError(reason.message)); }, []);
  async function addUser(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/team/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.message ?? "Could not add this profile."); else { setUsers((current) => [...current, body.user]); setOpen(false); event.currentTarget.reset(); } setSaving(false); }
  const visible = users.filter((user) => `${user.name} ${user.email} ${user.department} ${user.team} ${user.role}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="team-directory"><div className="team-directory-head"><div><span className="section-eyebrow">PROFILE DIRECTORY / ROLE-AWARE</span><h2>People who make the work move.</h2><p>Each profile carries a role, department, team, and dashboard focus. Access is enforced by the session, not only by what the UI hides.</p></div><button className="team-add" onClick={() => setOpen(true)}><Plus size={15} /> Add team member</button></div><div className="team-tools"><label><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search people, teams, or roles" /></label><span>{visible.length} profiles</span></div><div className="team-grid">{visible.map((user) => <article className="team-card" key={user.id}><div className="team-avatar"><UserRound size={17} /></div><div className="team-card-main"><div className="team-card-title"><div><h3>{user.name}</h3><p>{user.title}</p></div><span className={`team-status ${user.status}`}>{user.status}</span></div><div className="team-meta"><span>{user.role}</span><span>{user.department}</span><span>{user.team}</span></div><small>{user.email}</small><div className="team-focus"><b>Dashboard focus</b><span>{getRoleProfile(user.role).focus}</span></div></div></article>)}</div>{!visible.length && !error && <div className="team-empty">No profiles match this search.</div>}{error && <div className="team-error">{error}</div>}{open && <div className="team-modal-backdrop"><form className="team-modal" onSubmit={addUser}><div className="team-modal-head"><div><span className="section-eyebrow">NEW WORKSPACE PROFILE</span><h2>Add a team member</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Close"><X size={17} /></button></div><label>Full name<input name="name" required placeholder="e.g. Anika Shah" /></label><label>Company email<input name="email" type="email" required placeholder="name@company.com" /></label><div className="team-form-grid"><label>Role<select name="role" defaultValue="employee">{roles.map((role) => <option key={role} value={role}>{role}</option>)}</select></label><label>Department<input name="department" defaultValue="General" /></label></div><div className="team-form-grid"><label>Team<input name="team" defaultValue="General" /></label><label>Title<input name="title" defaultValue="Team member" /></label></div><label>Initial password <span className="field-note">optional for an invited profile; minimum 12 characters</span><input name="password" type="password" minLength={12} placeholder="Create only when credentials are ready" /></label><button className="team-save" disabled={saving}>{saving ? "Creating profile..." : "Create profile"}<Check size={15} /></button></form></div>}</div>;
}
