"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, ArrowUpRight, BarChart3, BriefcaseBusiness, CalendarDays, Check, ChevronDown, CircleAlert, CircleDollarSign, Cloud, FileText, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageCircle, MoreHorizontal, Search, Settings2, ShieldCheck, Sparkles, Users, Workflow, X } from "lucide-react";
import { canAccessWorkspace, canAssignProjects } from "../../lib/access";
import { AssignProjectButton } from "../../components/AssignProjectButton";
import { WorkspaceCopilot } from "../../components/WorkspaceCopilot";
import "./dashboard.css";

const nav = [["Operations Console", LayoutDashboard, ""], ["CRM", Users, "crm"], ["Clients", Users, "clients"], ["Projects", BriefcaseBusiness, "projects"], ["Calendar", CalendarDays, "calendar"], ["Marketing", BarChart3, "marketing"], ["Finance", CircleDollarSign, "finance"], ["Documents", FileText, "documents"], ["Communication", MessageCircle, "communication"], ["Automation", Workflow, "automation"], ["AI Agents", Sparkles, "ai-agents"], ["Reports", Activity, "reports"], ["Integrations", Cloud, "integrations"], ["People intelligence", Users, "people-intelligence"], ["Access", ShieldCheck, "access"], ["Audit logs", FileText, "audit-logs"]] as const;
const roleLabels: Record<string, string> = { owner: "Owner", manager: "Operations manager", employee: "Team member", finance: "Finance", hr: "People & culture", client: "Client workspace" };
const queue = [{ tone: "amber", label: "Delivery risk", title: "Atlas Health sprint needs a decision", detail: "Deadline tomorrow · 4 tasks open · owner: Ravi Nair", action: "Review project" }, { tone: "blue", label: "Integration", title: "Google Ads is not connected", detail: "Marketing reporting is incomplete until an account is linked.", action: "Connect source" }, { tone: "violet", label: "Client moment", title: "Northstar quarterly review is due", detail: "Prepare the delivery summary before Friday's client meeting.", action: "Open client" }];
const changes = [["09:42", "Jamie Kim completed", "Technical SEO audit", "lime"], ["09:18", "New client note added", "Northstar Labs", "blue"], ["Yesterday", "Invoice #1048 marked paid", "£3,200 · Northstar Labs", "violet"], ["Yesterday", "Ravi moved a milestone", "Atlas Health · Sprint 02", "amber"]];
const delivery = [["northstar-website", "Northstar Labs", "Website architecture", "82%", "Healthy", "Review feedback", "lime", "Jamie Kim"], ["atlas-seo", "Atlas Health", "SEO growth sprint", "61%", "Watch", "Resolve 4 open tasks", "amber", "Ravi Nair"], ["morrow-launch", "Morrow Studio", "Launch systems", "44%", "In review", "Approve campaign plan", "violet", "Samira Patel"]];
function queueForRole(role: string) {
  if (role === "finance") return [{ tone: "amber", label: "Receivables", title: "Atlas Health invoice needs follow-up", detail: "Invoice #1047 · due today · approval required before sending", action: "Review invoice" }];
  if (role === "hr") return [{ tone: "violet", label: "People review", title: "Three evidence packs need calibration", detail: "Recognition, growth, and support signals are ready for human review.", action: "Open people intelligence" }];
  if (role === "client") return [{ tone: "blue", label: "Client moment", title: "Northstar quarterly review is due", detail: "Prepare the delivery summary before Friday's client meeting.", action: "Open client" }];
  if (role === "employee") return [{ tone: "amber", label: "My delivery", title: "Technical SEO audit needs review", detail: "One deliverable is ready for manager feedback.", action: "Open my work" }];
  return queue;
}

export default function DashboardPage() {
  const [menuOpen, setMenuOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [copilotOpen, setCopilotOpen] = useState(false); const [role, setRole] = useState("owner"); const [queueItems, setQueueItems] = useState(queue); const [query, setQuery] = useState("");
  useEffect(() => { fetch("/api/auth/session").then((response) => response.ok ? response.json() : null).then((session) => { if (session?.role) { setRole(session.role); setQueueItems(queueForRole(session.role)); } }).catch(() => undefined); }, []);
  const visibleChanges = useMemo(() => changes.filter((item) => { const text = item.join(" ").toLowerCase(); const allowed = role === "finance" ? text.includes("invoice") : role === "client" ? text.includes("client") || text.includes("northstar") : role === "hr" ? text.includes("jamie") : true; return allowed && text.includes(query.toLowerCase()); }), [query, role]);
  async function signOut() { await fetch("/api/auth/sign-out", { method: "POST" }); window.location.href = "/sign-in"; }
  const managerCanAssign = canAssignProjects(role);
  const visibleDelivery = useMemo(() => role === "client" ? delivery.filter(([id]) => id === "northstar-website") : role === "employee" ? delivery.filter(([, , , , , , , assignee]) => assignee === "Jamie Kim") : delivery, [role]);
  return <div className="dashboard-shell">
    <aside className={`dashboard-sidebar ${menuOpen ? "open" : ""}`}><div className="dashboard-brand"><span className="dashboard-mark">LR</span><span>L. R. <b>Tech Solutions</b></span><button onClick={() => setMenuOpen(false)} className="sidebar-close" aria-label="Close navigation"><X size={17} /></button></div><div className="workspace-switcher"><span className="workspace-avatar">LR</span><span><b>L. R. Tech Solutions</b><small>{roleLabels[role] ?? "Company workspace"}</small></span><ChevronDown size={14} /></div><div className="side-label">Company operations</div><nav className="dashboard-nav">{nav.filter(([, , slug]) => !slug || canAccessWorkspace(role, slug)).map(([label, Icon, slug]) => <Link href={slug ? `/dashboard/${slug}` : "/dashboard"} key={label} className={!slug ? "active" : ""} onClick={() => setMenuOpen(false)}><Icon size={16} /><span>{label}</span>{!slug && <i>1</i>}</Link>)}</nav><div className="side-label">Workspace</div><nav className="dashboard-nav"><Link href="/dashboard/team"><Users size={16} /><span>Team</span></Link><Link href="/dashboard/settings"><Settings2 size={16} /><span>Settings</span></Link></nav><div className="sidebar-bottom"><div className="workspace-note"><LockKeyhole size={16} /><b>Private workspace</b><small>Access is shaped by your role and assignment.</small></div><div className="user-row"><Link href="/dashboard/profile" className="user-profile-link"><span className="user-avatar">{role === "client" ? "CL" : "LR"}</span><span><b>{roleLabels[role] ?? "Workspace user"}</b><small>Signed-in session</small></span></Link><button onClick={signOut} aria-label="Sign out"><LogOut size={16} /></button></div></div></aside>
    <main className="dashboard-main"><header className="dashboard-topbar"><button className="dashboard-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open navigation"><Menu size={20} /></button><div className="dashboard-breadcrumb"><span>L. R. Tech Solutions</span><b>/</b><strong>Operations Console</strong></div><div className="dashboard-actions"><label className="global-search"><Search size={16} /><input aria-label="Search workspace" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search activity" /><kbd>Ctrl K</kbd></label><a className="view-site" href="/">View public site <ArrowUpRight size={14} /></a><button className="profile-trigger" onClick={() => setProfileOpen(!profileOpen)} aria-expanded={profileOpen}>{roleLabels[role] ?? "Workspace"}<ChevronDown size={13} /></button></div>{profileOpen && <div className="profile-menu"><span>{roleLabels[role] ?? "Workspace user"}</span><button onClick={signOut}><LogOut size={14} /> Sign out</button></div>}</header>
      <div className="dashboard-content"><div className="dashboard-heading"><div><span className="dashboard-eyebrow"><span className="status-pulse" /> Workspace snapshot · 21 September 2026</span><h1>Make the next<br /><em>right decision.</em></h1><p>One operating view for the clients, delivery, people, and systems behind L. R. Tech Solutions.</p></div><div className="heading-actions"><span className="data-badge"><Activity size={13} /> Seeded workspace</span><button className="new-button" onClick={() => setCopilotOpen(true)}><Sparkles size={16} /> Ask the workspace</button></div></div>
        <section className="status-rail" aria-label="Company status"><div><span className="status-label">BUSINESS PULSE</span><strong>Steady</strong><small>3 signals need review</small></div><div><span className="status-label">DELIVERY</span><strong className="amber-text">1 watch</strong><small>Atlas Health sprint</small></div><div><span className="status-label">CLIENT HEALTH</span><strong>Healthy</strong><small>2 reviews upcoming</small></div><div><span className="status-label">SYSTEMS</span><strong>3 connected</strong><small>Last sync · 8 min ago</small></div><div className="rail-updated"><span>DATA FRESHNESS</span><b>Seeded snapshot</b><small>Connect sources to go live</small></div></section>
        <section className="command-grid"><div className="decision-panel"><div className="panel-heading"><div><span className="panel-kicker">DECISION QUEUE / {queueItems.length}</span><h2>What needs attention</h2></div><button className="quiet-action">View all <ArrowUpRight size={14} /></button></div><div className="queue-list">{queueItems.map((item) => <article className="queue-item" key={item.title}><span className={`queue-mark ${item.tone}`}><CircleAlert size={16} /></span><div><span className="queue-label">{item.label}</span><h3>{item.title}</h3><p>{item.detail}</p><button onClick={() => setQueueItems((items) => items.filter((current) => current.title !== item.title))}>{item.action} <ArrowRight size={14} /></button></div><button className="dismiss-action" onClick={() => setQueueItems((items) => items.filter((current) => current.title !== item.title))} aria-label={`Dismiss ${item.title}`}><Check size={15} /></button></article>)}{queueItems.length === 0 && <div className="empty-queue"><CheckCircleIcon /><b>Nothing urgent in the queue.</b><span>New exceptions will appear here.</span></div>}</div></div><div className="change-panel"><div className="panel-heading"><div><span className="panel-kicker">CHANGE LEDGER</span><h2>What moved</h2></div><button className="quiet-action"><MoreHorizontal size={17} /></button></div><div className="change-list">{visibleChanges.map(([time, title, detail, tone]) => <div className="change-row" key={`${time}-${title}`}><span className={`change-dot ${tone}`} /><time>{time}</time><p><b>{title}</b><small>{detail}</small></p><ArrowUpRight size={14} /></div>)}{visibleChanges.length === 0 && <div className="empty-queue"><b>No matching activity.</b><span>Try another search term.</span></div>}</div></div></section>
        <section className="lower-grid"><div className="delivery-panel"><div className="panel-heading"><div><span className="panel-kicker">DELIVERY MAP</span><h2>Client work in motion</h2></div><Link href="/dashboard/projects" className="quiet-action">Open projects <ArrowUpRight size={14} /></Link></div><div className="delivery-head"><span>CLIENT / ENGAGEMENT</span><span>PROGRESS</span><span>HEALTH</span><span>NEXT DECISION</span></div>{visibleDelivery.map(([id, client, project, progress, health, next, tone, assignee]) => <div className="delivery-row" key={id}><div><span className={`client-sigil ${tone}`}>{client.slice(0, 2)}</span><p><b>{client}</b><small>{project} · {assignee}</small></p></div><div className="delivery-progress"><div><span style={{ width: progress }} /></div><small>{progress}</small></div><span className={`health-state ${tone}`}>{health}</span><span className="next-decision">{next}</span>{managerCanAssign ? <AssignProjectButton projectId={id} projectName={`${client} — ${project}`} /> : <ArrowUpRight size={15} />}</div>)}</div><div className="systems-panel"><div className="panel-heading"><div><span className="panel-kicker">OPERATING SIGNALS</span><h2>System health</h2></div><Link href="/dashboard/integrations"><ArrowUpRight size={15} /></Link></div><div className="system-row"><Cloud size={16} /><p><b>Data sources</b><small>3 connected · 7 available</small></p><span className="system-state watch">Incomplete</span></div><div className="system-row"><ShieldCheck size={16} /><p><b>Security posture</b><small>Session protected · secrets server-side</small></p><span className="system-state good">Protected</span></div><div className="system-row"><Workflow size={16} /><p><b>Automation</b><small>18 workflows · 1 needs review</small></p><span className="system-state watch">Review</span></div><div className="system-callout"><Sparkles size={15} /><span><b>Next best action</b><small>Connect one marketing source before the next client report.</small></span></div></div></section>
        <section className="focus-strip"><div><span className="panel-kicker">ROLE FOCUS · {roleLabels[role]?.toUpperCase() ?? "WORKSPACE"}</span><h2>{role === "client" ? "Keep your work transparent." : role === "employee" ? "Know what to move next." : role === "finance" ? "Protect the cash picture." : "Keep the whole system clear."}</h2></div><p>{role === "client" ? "Your projects, decisions, documents, and conversations in one place." : "The command center prioritizes exceptions first, then gives you the context and action to resolve them."}</p><button className="focus-button" onClick={() => setCopilotOpen(true)}>Open my focus <ArrowRight size={15} /></button></section>
      </div></main><WorkspaceCopilot role={role} roleLabel={roleLabels[role] ?? "workspace user"} open={copilotOpen} onClose={() => setCopilotOpen(false)} /></div>;
}

function CheckCircleIcon() { return <span className="empty-check"><Check size={16} /></span>; }
